from datetime import datetime
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, Field

from .client import Client


class BaseDocument(BaseModel):
    """BaseDocument"""

    """MongoDB Collection"""
    collection: ClassVar[str] = NotImplemented
    """Autogenerated _id"""
    object_id: Any = Field(alias="_id")
    """Short unique id"""
    id: str
    """Date last modified"""
    updated_at: datetime
    """Date created"""
    created_at: datetime

    def __init_subclass__(cls, *args, collection: Optional[str] = None, **kwargs):

        # NOTE: known issue in mypy
        # https://github.com/python/mypy/issues/4660
        super().__init_subclass__(*args, **kwargs)  # type: ignore

        if collection:
            cls.collection = collection
        else:
            cls.collection = f"{cls.__name__.lower()}s"

        Client._register(cls.collection, cls)
